// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    Banner: typeof import('./src/components/discover/Banner.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    Comment: typeof import('./src/components/songlist/Comment.vue')['default']
    Description: typeof import('./src/components/songlist/Description.vue')['default']
    IconGird: typeof import('./src/components/my/IconGird.vue')['default']
    IconList: typeof import('./src/components/discover/IconList.vue')['default']
    ILike: typeof import('./src/components/my/ILike.vue')['default']
    PlayControl: typeof import('./src/components/PlayControl.vue')['default']
    PlayerWidget: typeof import('./src/components/playerinterface/PlayerWidget.vue')['default']
    RecommendPalylist: typeof import('./src/components/discover/RecommendPalylist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHistory: typeof import('./src/components/search/SearchHistory.vue')['default']
    SearchResultList: typeof import('./src/components/search/SearchResultList.vue')['default']
    SongItem: typeof import('./src/components/songlist/SongItem.vue')['default']
    SongMenu: typeof import('./src/components/songlist/SongMenu.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    UserInfo: typeof import('./src/components/my/UserInfo.vue')['default']
  }
}
